# Generated by Django 4.2.14 on 2024-08-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bag_text", models.CharField(max_length=200)),
                ("img_url", models.CharField(max_length=200)),
            ],
        ),
    ]
