# Generated by Django 4.2.14 on 2024-08-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0002_bag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer_Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("tag", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("img_url", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("street_address", models.CharField(max_length=100)),
                ("apt_number", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("customer_email", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("status", models.CharField(default="submitted", max_length=20)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AsianFashion.item"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Bag",),
        migrations.RemoveField(model_name="choice", name="question",),
        migrations.RemoveField(model_name="choice", name="votes",),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(name="Question",),
        migrations.AddField(
            model_name="customer_cart",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AsianFashion.item"
            ),
        ),
    ]
