# Generated by Django 4.2.14 on 2024-08-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0003_customer_cart_item_order_delete_bag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="height_cm",
            field=models.IntegerField(default=40, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="length_cm",
            field=models.IntegerField(default=40, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="material",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="width_cm",
            field=models.IntegerField(default=40, null=True),
        ),
    ]
