# Generated by Django 4.2.14 on 2024-08-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0004_item_height_cm_item_length_cm_item_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="height_cm", field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="item", name="length_cm", field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="item",
            name="material",
            field=models.CharField(default="PU", max_length=30),
        ),
        migrations.AlterField(
            model_name="item", name="width_cm", field=models.IntegerField(default=40),
        ),
    ]
