# Generated by Django 4.2.14 on 2024-08-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0009_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="item",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AsianFashion.item",
            ),
        ),
    ]
