# Generated by Django 4.2.14 on 2024-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0011_customer_cart_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="choice_text",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
