# Generated by Django 4.2.14 on 2024-08-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0012_order_choice_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="choice_text",),
        migrations.AddField(
            model_name="order",
            name="choice",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AsianFashion.choice",
            ),
        ),
    ]
