# Generated by Django 4.2.14 on 2024-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0013_remove_order_choice_text_order_choice"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="height_cm",),
        migrations.RemoveField(model_name="item", name="length_cm",),
        migrations.RemoveField(model_name="item", name="width_cm",),
        migrations.AddField(
            model_name="item", name="height", field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name="item", name="length", field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name="item", name="width", field=models.FloatField(default=40),
        ),
    ]
