# Generated by Django 4.2.14 on 2024-08-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0014_remove_item_height_cm_remove_item_length_cm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer", name="email", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
