# Generated by Django 4.2.14 on 2024-08-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0015_alter_customer_email_alter_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_summary",
            field=models.CharField(default=None, null=True, max_length=10000),
        ),
    ]
