# Generated by Django 4.2.14 on 2024-08-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0017_alter_order_order_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_summary",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
