# Generated by Django 4.2.14 on 2024-08-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0018_alter_order_order_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="uuid",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
