# Generated by Django 4.2.14 on 2024-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsianFashion", "0019_customer_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="uuid",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
